### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by ghost**
Remove extra bytes of trailing whitespace.

### CODE REVIEW

**Comment by compteccharan** [comment]
epic dude

**Comment by GrpeApple** [comment]
indeed, 114 files

**Comment by compteccharan** [comment]
cool but wait for cw khan answer

**Comment by Khanmanan** [comment]
Dude its look like u just download and import to ur git I don't see any changes

**Comment by GrpeApple** [comment]
> Dude its look like u just download and import to ur git I don't see any changes

[...](https://github.com/Khanmanan/automod-bot/pull/16/files)

**Comment by GrpeApple** [comment]
I removed the trailing whitespace.
For example
```
this                
```
has trailing whitespace
while
```
this
```
has no trailing whitespace.

**Comment by GrpeApple** [comment]
image

**Pull request closed without merging**
